### ISSUE TITLE
Can I install this on Solus OS with Mate Desktop ? 

### ISSUE THREAD

**Issue by abrhambas01** [grocid/macos-arc#1]
I'm newbie to customizing in linux but I have a lot of questions here 

1. Can I use it on SOLUS with Mate Desktop ? 
2. How do install it I'm using eopkg

**Comment by grocid** [comment]
Probably, yes. Moving the `macos-arc` folder to `/usr/share/themes` (for system-wide usage) should suffice. That should make it pop up in the _Appearance_ settings.

**Comment by abrhambas01** [comment]
Thank you friend :+1:
